"""
SQLAlchemy ORM Models - Subject

Represents a learning domain (e.g., Python, Constitutional Law, Organic Chemistry).
Subjects are DYNAMICALLY created by the LLM — not hardcoded.
Any domain the user wants to learn becomes a Subject.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, DateTime, JSON, Boolean, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class Subject(Base):
    """
    A learning domain dynamically generated by the Planner Agent.
    Can be anything: Python, Law, Medicine, Music Theory, etc.
    """
    __tablename__ = "subjects"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")

    # Domain category for smart routing (cs, law, medicine, arts, science, custom)
    # Helps the LLM router decide which provider handles this subject best
    domain: Mapped[str] = mapped_column(String(50), default="custom")

    # Category within domain (e.g., "programming" within "cs")
    category: Mapped[str] = mapped_column(String(100), default="general")

    # IDs of subjects that should be learned first
    prerequisite_ids: Mapped[list] = mapped_column(JSON, default=list)

    # Whether this subject was generated by the LLM (vs manually seeded)
    is_generated: Mapped[bool] = mapped_column(Boolean, default=True)

    # Extra domain-specific configuration
    # e.g., {"has_coding": true, "assessment_types": ["mcq", "coding"]}
    metadata_: Mapped[dict] = mapped_column("metadata", JSON, default=dict)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    topics: Mapped[list["Topic"]] = relationship(
        back_populates="subject", cascade="all, delete-orphan"
    )
    learning_paths: Mapped[list["LearningPath"]] = relationship(
        back_populates="subject", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Subject(id={self.id}, name={self.name}, domain={self.domain})>"
