"""
SQLAlchemy ORM Models - Topic

A single learnable unit within a Subject.
Topics are generated by the Planner Agent and form
the building blocks of learning paths.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, DateTime, JSON, Boolean, Integer, Text, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.database import Base


class Topic(Base):
    """
    A single concept/skill within a subject.
    e.g., "List Comprehensions" in Python, "Tort Law" in Law.
    Generated dynamically by the Planner Agent.
    """
    __tablename__ = "topics"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    subject_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("subjects.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")

    # Difficulty from 1 (easiest) to 10 (hardest)
    difficulty_level: Mapped[int] = mapped_column(Integer, default=1)

    # Order within the subject (for sequential learning)
    order_index: Mapped[int] = mapped_column(Integer, default=0)

    # IDs of topics that must be mastered before this one
    prerequisites: Mapped[list] = mapped_column(JSON, default=list)

    # How this topic should be taught/tested
    # theory = Q&A only, coding = code challenges, mixed = both
    content_type: Mapped[str] = mapped_column(
        String(20), default="theory"  # theory | coding | mixed
    )

    # Whether this topic was LLM-generated
    is_generated: Mapped[bool] = mapped_column(Boolean, default=True)

    # What the user should know after mastering this topic
    learning_objectives: Mapped[list] = mapped_column(JSON, default=list)

    # Estimated time to learn (in minutes)
    estimated_minutes: Mapped[int] = mapped_column(Integer, default=30)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    subject: Mapped["Subject"] = relationship(back_populates="topics")
    knowledge_states: Mapped[list["KnowledgeState"]] = relationship(
        back_populates="topic", cascade="all, delete-orphan"
    )
    test_results: Mapped[list["TestResult"]] = relationship(
        back_populates="topic", cascade="all, delete-orphan"
    )
    weaknesses: Mapped[list["WeaknessMap"]] = relationship(
        back_populates="topic", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Topic(id={self.id}, name={self.name}, difficulty={self.difficulty_level})>"
